spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://localhost:3306/meghana
spring.datasource.username=root
spring.datasource.password=Gm#3ghana
spring.jpa.hibernate.ddl-auto=create



server.servlet.context-path=/api
